name: Continuous API Call

on:
  schedule:
    - cron: '0 13 * * *' # Runs every day at 1:00 PM UTC

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run JavaScript script
        run: |
          node Cron.js
