name: Continuous API Call

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * 1-5' # Runs every minute

jobs:
  api_call:
    runs-on: ubuntu-latest

     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
    
     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
         java-version: '11'
    
     - name: Build with Maven
       run: mvn -B package --file pom.xml
    
     - name: Run Java script
       run: java -classpath target/classes APICaller
