name: Continuous API Call

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * 1-5' # Runs every minute

jobs:
  api_call:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run API call script
      run: go run cron.go
